language: php

php:
  - 5.6
  - 7.0

sudo: false

env:
  global:
    - DEFAULT=1
    - PHPCS=1

matrix:
  fast_finish: true

install:
  - composer self-update
  - composer install --prefer-dist

before_script:
  - phpenv rehash
  - set +H

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then phpunit; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then ./vendor/bin/phpcs -n -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src; fi"

notifications:
  email: false
